apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: application-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  selector:
    matchLabels:
      app: application-service
  replicas: 1
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: 192.168.1.104:5000/application-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8848
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 2000Mi
          readinessProbe:
            tcpSocket:
              port: 8848
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: REGISTRY_IP # 注册中心地址
              value: ""
            - name: REGISTRY_PORT # 注册中心端口
              value: ""
            - name: KUBESPHERE_URL # Kubesphere
              value: ""
            - name: KUBESPHERE_USERANME # Kubesphere用户名
              value: ""
            - name: KUBESPHERE_PASSWORD # Kubesphere密码
              value: ""
